version: '3.5'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234567890
    volumes:
      - ./docker/data/db:/var/lib/mysql

  Flask-Back-End:
    container_name: flask-app
    restart: always
    build:
      context: ./real_flask_app/
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./real_flask_app:/usr/src/app
    depends_on:
      - "db"

  React-Front-end:
    container_name: react-app
    build:
      context: ./React-Front-End
      dockerfile: Dockerfile
    volumes:
      - './React-Front-End:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - "Flask-Back-End"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://192.168.99.100:5000
